import random


def get_topics():
    science = [
        "Evolution of the Printing Press and Its Impact on Society",
        "Discovery of Penicillin and the Revolution in Antibiotics",
        "Development and Ethical Implications of Cloning Technology",
        "How the Theory of Quantum Mechanics Transformed Our View of Reality",
        "Role of the Transistor in Modern Electronics",
        "CRISPR and the Future of Genetic Modification",
        "Internet of Things: Connectivity and Its Societal Impacts",
        "Blockchain Technology: Beyond Bitcoin",
        "Environmental and Technological Challenges of Nuclear Power",
        "Artificial Intelligence: The Path Toward Singularity",
        "Hubble Telescope and Its Contributions to Astronomy",
        "Rise of Renewable Energy: Solar and Wind Technologies",
        "Impact of Mobile Computing on Global Communication",
        "Nanotechnology: Manipulating Matter at the Atomic Level",
        "Development of the Periodic Table and Its Influence on Chemistry",
        "Science of Vaccination and Its Sociopolitical Impact",
        "Evolutionary Implications of the Human Genome Project",
        "How Machine Learning is Shaping the Future of Various Industries",
        "Discovery of Insulin and Its Impact on Diabetes Management",
        "Theoretical Physics: String Theory and Its Controversies",
        "Technological Advancements in Deep Sea Exploration",
        "Development of Autonomous Vehicles and Their Future",
        "3D Printing: Applications and Future Potential",
        "History and Future of Space Exploration",
        "Role of Algorithms in Modern Life",
        "Cybersecurity: Protecting Information in the Digital Age",
        "Advancement of Augmented Reality and Virtual Reality",
        "Biotechnology in Agriculture: Revolutionizing Farming",
        "Future of Quantum Computing",
        "Smart Cities: Integration of Technology in Urban Planning",
        "Evolution of the Internet: From ARPANET to the Modern Web",
        "Impact of Mobile Technology on Global Communication",
        "Gene Editing Technologies: CRISPR and Beyond",
        "Role of Artificial Intelligence in Healthcare",
        "Discovery and Applications of Penicillin",
        "Development of Quantum Computing",
        "Nanotechnology: Current Innovations and Future Prospects",
        "History and Future of Space Exploration",
        "Blockchain Technology: Beyond Bitcoin",
        "Science of Climate Change: Causes and Solutions",
        "Theories of Evolution: From Darwin to Modern Synthesis",
        "Development and Impact of Nuclear Energy",
        "Rise of Autonomous Vehicles: Technology and Ethics",
        "Virtual Reality: Technology, Applications, and Social Implications",
        "History of the Electric Grid and Renewable Energy Integration",
        "Innovations in Biotechnology: The Human Genome Project",
        "Robotics: Advancements, Ethics, and the Future of Work",
        "Discovery of Insulin and Its Impact on Diabetes Management",
        "Internet of Things (IoT): Smart Devices and Privacy Concerns",
        "Advances in Material Science: Superconductors and Beyond",
        "Role of Technology in Modern Warfare",
        "Cybersecurity: Protecting Information in the Digital Age",
        "Science Behind Renewable Energy Sources: Wind, Solar, and Hydro",
        "Water Purification Technologies and Their Global Impact",
        "Physics of Black Holes and What They Tell Us About the Universe",
        "Development of the Periodic Table and Its Impact on Chemistry",
        "Role of Algorithms in Shaping Social Media",
        "Innovations in 3D Printing: Applications in Medicine and Manufacturing",
        "Science of Habit: Neurological Processes and Behavioral Outcomes",
        "Discovery and Development of X-rays",
    ]

    history =[
        "Rise and Fall of the Roman Empire",
        "Mongol Invasion: Global Impact and Historical Significance",
        "Renaissance: Key Figures and Their Contributions to Modern Thought",
        "French Revolution: Causes, Events, and Outcomes",
        "Impact of the Columbian Exchange on the Old and New Worlds",
        "Industrial Revolution: Technological Advances and Societal Changes",
        "World War I: The Great War and Its Aftermath",
        "Russian Revolution: From Imperial Rule to Soviet Power",
        "Roaring Twenties: Cultural Revolution and Economic Boom",
        "Holocaust: Historical Evidence and Its Lasting Impact",
        "Decolonization of Africa: Historical Context and Modern-Day Implications",
        "Civil Rights Movement in America: Key Events and Figures",
        "Fall of the Berlin Wall: Symbol of the End of the Cold War",
        "Cultural Revolution in China: Policies and Personal Stories",
        "Rise of Islamic Empires: Contributions to Science and Culture",
        "American Revolution: From Colonialism to Independence",
        "History of the Silk Road and Its Impact on Trade and Culture",
        "Vietnam War: Perspectives and Historiography",
        "Byzantine Empire: Religion, Politics, and Artistic Contributions",
        "Spanish Inquisition: Religious Persecution and Historical Analysis",
        "Great Explorers: Columbus, Magellan, and Others",
        "Ottoman Empire: Administration, Culture, and Decline",
        "Meiji Restoration: Japan's Rapid Modernization",
        "Age of Enlightenment: Philosophers and Their Ideas",
        "Mughal Empire: Art, Architecture, and Administration",
        "Impact of the Spice Trade on European Economic Development",
        "Partition of India: Causes and Consequences",
        "Aztec and Inca Civilizations: Pre-Colombian Culture and Conquest",
        "Scientific Revolution: Key Discoveries and Influential Scientists",
        "Crusades: Religious Motives and Economic Impacts"


    ]

    phil = [
        "Concept of Justice in Plato's Republic",
        "Nietzsche's Philosophy of the Übermensch",
        "Kantian Ethics: The Categorical Imperative",
        "Philosophy of Mind: Consciousness and Cognition",
        "Utilitarianism: The Greatest Happiness Principle",
        "Existentialism: Freedom and Responsibility",
        "Ethics of Care: A Feminist Approach to Moral Theory",
        "Stoicism and Modern Resilience",
        "Social Contract Theory by Rousseau",
        "Confucianism: Ethics and Political Philosophy",
        "Problem of Evil in Theodicy",
        "Virtue Ethics: Aristotle's Contributions",
        "Postmodernism: Critiques and Perspectives",
        "Ethics of Artificial Intelligence",
        "Trolley Problem and Moral Dilemmas",
        "Environmental Ethics: Philosophical Approaches to Nature",
        "Eastern vs. Western Philosophies: A Comparative Analysis",
        "Philosophy of Language: Meaning and Context",
        "Anarchism: Philosophical and Ethical Foundations",
        "Concept of Liberty in Political Philosophy",
        "Buddhist Philosophy: The Concept of Suffering and Liberation",
        "Philosophy of Science: Paradigms and Progress",
        "Hegelian Dialectics and Historical Development",
        "Ethics of Globalization: Equity, Economy, and Environment",
        "Philosophy of Education: Aims and Methods",
        "Animal Rights: Ethical Theories and Debates",
        "Phenomenology of Perception",
        "Epistemology of Disagreement: How We Know What We Know",
        "Ethics of Consumption: Materialism and Sustainability",
        "Influence of Technology on Human Values",
    ]


    econ =[
    "Principles of Keynesian Economics and Its Modern Applications",
    "Neoliberalism: Origins, Principles, and Global Impact",
    "Role of Government in Market Economies",
    "Comparative Economic Systems: Socialism vs. Capitalism",
    "Economics of Climate Change: Costs and Strategies",
    "Modern Monetary Theory: A New Approach to Economic Management",
    "Political Economy of Trade Wars",
    "Rise and Impact of Populism in Western Democracies",
    "Universal Basic Income: Economic and Social Implications",
    "Influence of Political Ideologies on International Relations",
    "Marxism: Theory and Practice in Contemporary Societies",
    "Fiscal Policy: Tools, Goals, and Outcomes",
    "Economics of Healthcare: Challenges and Solutions",
    "Behavioral Economics: How Psychology Affects Economic Decisions",
    "Gig Economy: Impacts on Labor and Regulation",
    "Future of Work: Automation, AI, and Societies",
    "Economic Inequality: Causes, Consequences, and Policies",
    "Politics of Energy: Resources, Conflicts, and Transitions",
    "Global Financial Crisis of 2008: Causes and Aftermath",
    "Economic Sanctions: Effectiveness and Ethical Considerations",
    "Economics of Education: Returns on Investment and Policy Implications",
    "Corruption and Economic Development: Causes and Cures",
    "Role of Central Banks in Global Economics",
    "Cryptocurrencies: Disrupting Traditional Financial Systems",
    "Impact of Globalization on Local Economies",
    "Politics of Environmental Policy",
    "Political Theories of Democracy and Authoritarianism",
    "Supply Chain Economics: Principles and Challenges",
    "Role of Innovation and Entrepreneurship in Economic Growth",
    "Political Campaign Finance: Laws, Ethics, and Effects",
    ]

    lit = [
    "Influence of Greek Mythology on Western Literature",
    "Modernism vs. Postmodernism in Literature and Art",
    "Harlem Renaissance: Art, Literature, and Music",
    "Impact of Shakespeare on the English Language",
    "Surrealism: Breaking Cultural and Artistic Boundaries",
    "Role of Fairy Tales in Cultural Education",
    "Beat Generation: Literary Innovations and Cultural Critique",
    "Romanticism: Emotion and Nature in Art and Literature",
    "Japanese Haiku: Form, Evolution, and Cross-Cultural Adoption",
    "Lost Generation: Expatriate Writers of the 1920s",
    "Gothic Literature: Exploring the Darker Side of Human Nature",
    "Dadaism: An Artistic and Literary Antidote to World War I",
    "Magical Realism: Blending the Real and the Fantastic",
    "Art of the Renaissance and Its Impact on Modern Aesthetics",
    "Russian Novel: Themes, Evolution, and Influence",
    "French New Wave: Cinema and Literature",
    "African-American Literature: Themes, History, and Impact",
    "Influence of Chinese Calligraphy on East Asian Art",
    "Cubism and Its Challenge to Traditional Art Forms",
    "Victorian Novel: Society, Morality, and Technology",
    "Latin American Literature: Magical Realism and Beyond",
    "Symbolist Movement in Literature and Art",
    "Modern Graphic Novel: Evolution and Cultural Relevance",
    "Feminist Literature: Waves, Key Works, and Impacts",
    "Intersection of Art and Technology: A New Aesthetic",
    "Expressionism: Emotion and Response in Art",
    "Role of Art in Social and Political Protest",
    "Impact of Post-Colonial Literature on Understanding Empire",
    "Art Nouveau and Art Deco: Style and Philosophy",
    "Transcendentalism in American Literature and Culture        ",
    ]

    health=[
        "Psychology of Stress and Coping Mechanisms",
        "Neuroplasticity: How the Brain Rewires Itself",
        "Biopsychosocial Model of Health",
        "Impact of Nutrition on Mental Health",
        "Autism Spectrum Disorders: Understanding and Innovations in Care",
        "Role of Genetics in Mental Health Disorders",
        "Attachment Theory: Developmental Psychology and Relationships",
        "Opioid Crisis: Causes, Consequences, and Solutions",
        "Sleep and Its Effects on Psychological Well-being",
        "Gut-Brain Axis: How the Microbiome Influences Mood and Behavior",
        "Cognitive Behavioral Therapy and Its Applications",
        "Health Benefits of Mindfulness and Meditation",
        "Schizophrenia: Symptoms, Theories, and Treatments",
        "Psychology of Addiction: From Substance Use to Behavioral Addictions",
        "Post-Traumatic Stress Disorder (PTSD): Mechanisms and Management",
        "Role of Exercise in Cognitive Function and Mental Health",
        "Impact of Chronic Pain on Psychological Health",
        "Eating Disorders: Types, Causes, and Treatments",
        "Science of Happiness: Factors and Psychological Approaches",
        "Theories of Personality: Freud, Jung, and Beyond",
        "Psychological Impact of Social Media Usage",
        "Gender Dysphoria: Psychological and Biological Perspectives",
        "Neuroscience of Learning and Memory",
        "Role of Inflammation in Depression and Anxiety",
        "Psychology of Aging: Cognitive Decline and Emotional Well-being",
        "Behavioral Economics: How Psychological Theory Explains Economic Decision Making",
        "Influence of Hormones on Behavior and Mood",
        "Psychological Resilience: Factors and Strategies for Development",
        "Impact of Climate Change on Mental Health",
        "Art Therapy: Principles, Applications, and Benefits        ",
    ]






    return [random.choice(science), 
            random.choice(history),
            random.choice(phil),
            random.choice(econ),
            random.choice(lit),
            random.choice(health)
            ]