"""Remove unique constraint on tags

Revision ID: 305581ac031a
Revises: e34d9d338652
Create Date: 2024-08-11 08:11:31.879264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305581ac031a'
down_revision: Union[str, None] = 'e34d9d338652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('tags_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_unique_constraint('tags_name_key', ['name'])

    # ### end Alembic commands ###
