"""Add action flag to msg table

Revision ID: 344d3e529ef3
Revises: 3714623c59ec
Create Date: 2024-07-03 08:42:33.574632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344d3e529ef3'
down_revision: Union[str, None] = '3714623c59ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable
    op.add_column('messages', sa.Column('show_actions', sa.Boolean(), nullable=True))

    # Step 2: Update all rows to have a value
    op.execute('UPDATE messages SET show_actions = false')  # or true, depending on your needs

    # Step 3: Alter the column to be non-nullable
    with op.batch_alter_table("messages") as batch_op:
        batch_op.alter_column('show_actions', nullable=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'show_actions')
    # ### end Alembic commands ###
