name: Blob storage website CI

env:
  AZURE_SITE_STORAGE_ACCOUNT: learnysite
  AZURE_SITE_CONTAINER: sc-website
  AZURE_CDN_PROFILE: learny-cdn
  AZURE_CDN_ENDPOINT: learny-cdn-endpoint
  AZURE_RESOURCE_GROUP: rg-learny
  AZURE_FUNCTIONAPP_NAME: ""
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ""
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ""

on:
    push:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    # setup nodejs environment
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: "18.16.1"

    # cache the dependencies to speed up the build
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # install dependencies
    - name: Install dependencies
      run: |
        cd frontend
        npm i

    # build the react app
    - name: Build
      run: |
        cd frontend
        npm run build

    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name $AZURE_SITE_STORAGE_ACCOUNT --source ./frontend/dist --destination $AZURE_SITE_CONTAINER
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name $AZURE_CDN_PROFILE --name $AZURE_CDN_ENDPOINT --resource-group $AZURE_RESOURCE_GROUP




    # - name: Setup Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.11

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Zip Python directory
    #   run: |
    #     zip -r functionapp.zip .

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: functionapp
    #     path: functionapp.zip

    # - name: Download artifact
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: functionapp

    # - name: 'Run Azure Functions Action'
    #   uses: Azure/functions-action@v1
    #   id: fa
    #   with:
    #     app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
    #     package: functionapp.zip
    #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    #     respect-pom-xml: false    


  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()